### ISSUE TITLE
让自定义模型支持上传图片

### ISSUE THREAD

**Issue by IrisRainbowNeko** [jmgaooo/ChatGPT-Next-APP#3]
让自定义模型能支持上传图片，比如gpt-4o, sonnet 3.5之类的

**Comment by jmgaooo** [comment]
这个app项目的原理是基于https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web进行的包装，自定义模型上传图片需要nextweb支持此功能，目前还没考虑对nextweb二次开发
